### ISSUE TITLE
Storybook Documentation - Component: FormCaptionGroup

### ISSUE THREAD

**Issue by angelicahoyss** [deven-org/B01LER-Kitchen#704]
#### Description / User Story

With this task we want to make the FormCaptionGroup Component page in Storybook look like the [template](https://www.figma.com/file/Sg2Uox6PchuAsMKY4ShXku/StorybookTemplate?type=design&node-id=1-1072&mode=design&t=qJ4f7V5skw35QEXC-0) from design.

----
#### Acceptance Criteria
- [x] Component Page has the same structure as the design template (in the following order):
   - [x] Headline & Intro Text incl. a list of anchor links to all following sections
   - [x] Docs Area with Example and all Props (see which props should be displayed for this component in the section below)
   - [x] ~Appearance~
      - [x] ~SizeVariant (incl. sizeVariant = SM, MD, LG)~
   - [x] ~Dependencies~
      - [x] ~FormCaption Component~
- [x] Component Page includes the texts as defined in the section below (incl. non default values for the shown examples)
- [x] Component Page text styles (uppercase, lowercase, spacing) correspond the the design template
- [x] Component Page spacing corresponds to design template
- [x] Component Page colours correspond to design template
- [x] Both FormCaption and FormCaptionGroup should be on the same level - nested inside the Internal Components folder in Storybook sidebar

----
#### Props

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "FormCaptionGroup" for all props that should be displayed for the component, incl. their description, default values and the type of controls. Props that do not appear and that can be removed, should also be removed (not including theme for example, because this is needed for all components, but still not part of the props section).

If the props in the list are not the same as the component currently uses, just leave a comment in column G in the excel and a follow-up task will be created. Fixing the components is not part of this ticket.

----
#### Content / Texts

See [this table](https://ts.accenture.com/:x:/r/sites/b01ler-core/_layouts/15/Doc.aspx?sourcedoc=%7Bb2cc9fb8-5c39-4049-9652-a4e6bbe09ef1%7D&action=editnew) page "Documentation Texts" for all texts that should be displayed for the component. Filter column A in cell A3 to only show you the texts of this components.

For the texts please change "[component name]" with "Form Caption Group" and "[componentName]" with "formCaptionGroup".

Also all the examples in the documentation below the Props should not use the default values, but they should use descriptive texts for Label, Placeholder and other text fields. Some examples are already given in the template.

----
#### Background information
- Example of a collapsible Props Section can be seen [here](https://www.kickstartds.com/storybook/?path=/docs/base-button--solid)

**Comment by thrbnhrtmnn** [comment]
Feedback @RubirajAccenture : 

- [ ] Please adjust the folder structure a bit, so that under "Internal Components" there is one folder for "Form Caption" and an additional one for "Form Caption Group"
- [ ] Headline: Please change headline from "FormCaptionGroup" to "Form Caption Group" (adding a space inbetween)
- [ ] Intro: Please change the intro to the text from the [Excel Document](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=3qXc8S): "The Form Caption Group is a combination of two Form Caption components, which allow to show both a hint and an error message or only one of each. It utilizes a slot element to render hint and error variants of Form Caption component. Displaying properties of the Form Caption components inside the slot is still work in progress and currently not displayed on this page. For more information have a look at the Dependencies section below. "
- [ ] Props Panel: Please list the size prop under the "Appearance" section in the panel (if this is possible with just one prop)
- [ ] Props Panel: Please add the descriptions as defined in the Excel to the prop: "Choose size of the component.". Also please make the size selection a radio instead of a select.


@angelicahoyss , I think we need to adjust all the component documentations, where we are utilising slots (Form Caption Group and Button Group). In both the Form Caption Group as well as the Button Group there is only one sizing prop, that can change the spacing in between the two slot components. Therefor I think the documentation would be sufficient, if we just explain this and then link to the components that should be placed in the slots. As we are also not able to really show the change of the sizing prop properly, I would also say that the whole documentation should be done with just a few sentences under the Intro text. The Table of Content can also be removed then.

My suggestion for the intro of the Form Caption Group would be:
> "The Form Caption Group is a combination of two Form Caption components, which allow to show both a hint and an error message or only one of each. 
> 
> Technically both instances of the Form Caption are placed inside two slots that are stacked above each other. The Form Caption Group only has one property named size to change the spacing in between the slots depending on the size of the component. Currently the spacing is the same for all sizes (SM, MD & LG). For more information have a look at the internal Form Caption [link to Form Caption component] component."

Do you agree with this approach? And do you want to adjust the documentation, also for the Button Group?

**Comment by angelicahoyss** [comment]
@thrbnhrtmnn Hey Thorben, I actually adjusted the Form Caption Group right before xmas to accommodate the slots.  
The part you wrote "Technically both instances of the Form Caption are placed inside two slots that are stacked above each other." are in intro as "It utilizes a slot element to render hint and error variants of Form Caption component." but we can adjust the text (add stacked above each other, I think that sounds great). I looked at the code and I saw one slot element that renders both of these, but we could ask the devs for details :) 
I think I would leave it as it is for consistency, because Form Caption Group is done and I can of course adjust the button group. But we can chat :)

**Comment by angelicahoyss** [comment]
@thrbnhrtmnn Regarding the sizing, is this a variable, could the users set their own spacing for each size variant? If that's the case I'd write something straight forward, like - in addition to "The size variant influences the spacing between the two Form Captions", we could add "In this instance, we have configured the spacing token value to 0 for each of the three size variants. However, this token can be adjusted according to specific requirements (or your requirements)"

**Comment by thrbnhrtmnn** [comment]
Hey @RubirajAccenture , I discussed the documentation with @angelicahoyss yesterday and we updated the texts in the Excel. You can start implementing the Feedback from my last comment now :-)

If you have questions please reach out to @angelicahoyss or me.

**Comment by thrbnhrtmnn** [comment]
Hey @RubirajAccenture , FYI Design already updated the values for the sizes prop, so I also updated two texts:
- Intro: I removed "Currently the spacing is the same for all sizes (SM, MD & LG). "
- Prop Description of Size: I removed " In this instance, we have configured the spacing token value to 0.25 rem  for each of the three size variants."

**Comment by thrbnhrtmnn** [comment]
Hey @RubirajAccenture , here is my feedback for the Form Caption Group:

- [ ] Intro: Please change the text from "...at the internal Form Caption Form Caption Component..." to "...at the internal Form Caption component..." and also fix the link to the Form Caption.
- [ ] Please make sure, that the update on develop which came with #734 are also in your branch before you merge it. This will result in the spacing between the two captions to change when changing the size.
- [ ] Props Panel: Please add the following description for the size prop: "Choose size of the component. The size variant influences the spacing between the two Form Captions."
- [ ] Please remove the complete Appearance section below the props panel, including also the "Size" section and the example story.
- [ ] One optional thing I would also change: Can you swap the icon of the hint message in the default story from "blrError" to "blrInfo" and the icon of the error message from "blrError" to "blrErrorFilled"?

**Comment by thrbnhrtmnn** [comment]
Documentation looks great, once merged this issue can be closed :-)
